---
"Twitter":
  "BEARER_TOKEN": AAAAAAAAAAAAAAAAAAAAACpiOQEAAAAAMyuk84Cm5NCY53yG5k7YC5vw72A%3DNRC3ZxenARnC3hW6JR5eoBYWTk3IFNOdrAZkZ4jaRO7ibmDmo8
"Twitch":
  client_id: kvnfu73c7dp7iz2c5i9tq456jl4f0z
  client_secret: ebx8hrxjwyfes0dkg8m0ojxk1x2n1d
"rawg.io":  58f66f75d8124171bb55205683cd79ec
suggested_limit:  10
not_game_words:
- demo
- OST
- soundtrack
- trailer
incremental:
- site:   Grabbed
  type:   Reference
  method: incremental
- site:   Steam
  type:   Store
  method: incremental
- site:   TouchArcade
  type:   Review
  method: incremental
full:
- site:   Adventure Gamers
  type:   Database
  method: find_database
- site:   Adventure Gamers
  type:   Review
  method: find_reviews
- site:   Adventure Game Hotspot
  type:   Database
  method: find_database
- site:   Adventure Game Hotspot
  type:   Review
  method: find_reviews
- site:   Big Fish Games
  type:   Store
  method: full
- site:   GameBoomers
  type:   Review
  method: findReviews
- site:   GameBoomers
  type:   Walkthrough
  method: findWalkthroughs
- site:   GOG
  type:   Store
  method: find
- site:   HOTU
  type:   Reference
  method: find
- site:   Just Adventure
  type:   Review
  method: find_reviews
- site:   Just Adventure
  type:   Walkthrough
  method: find_walkthroughs
- site:   Mystery Manor
  type:   Review
  method: find_reviews
- site:   Mystery Manor
  type:   Walkthrough
  method: find_walkthroughs
- site:   Nice Game Hints
  type:   Walkthrough
  method: find
- site:   Steam
  type:   Store
  method: find
- site:   Turn Based Lovers
  type:   Review
  method: findReviews
rebase:
- site:   TouchArcade
  type:   Review
  method: find
test_full:
- site:   Adventure Game Hotspot
  type:   Database
  method: find_database
- site:   Turn Based Lovers
  type:   Review
  method: findReviews
test_incremental:
- site:   Mystery Manor
  type:   Walkthrough
  method: find_walkthroughs
- site:   Steam
  type:   Store
  method: find
