---
"Twitter":
  "BEARER_TOKEN": AAAAAAAAAAAAAAAAAAAAACpiOQEAAAAAMyuk84Cm5NCY53yG5k7YC5vw72A%3DNRC3ZxenARnC3hW6JR5eoBYWTk3IFNOdrAZkZ4jaRO7ibmDmo8
"Twitch":
  client_id: kvnfu73c7dp7iz2c5i9tq456jl4f0z
  client_secret: ebx8hrxjwyfes0dkg8m0ojxk1x2n1d
"rawg.io":  58f66f75d8124171bb55205683cd79ec
MobyGames:  moby_BfnnHhYCrJYeUpdL94e3WQQm8ql
suggested_limit:  10
not_game_words:
- demo
- OST
- soundtrack
- trailer
problem:
train:
- site:   Grabbed
  type:   Reference
  method: incremental
  every:  0
overnight:
- site:   Adventure Game Hotspot
  type:   Database
  method: find_database
  every:  30
- site:   Adventure Game Hotspot
  type:   Review
  method: find_reviews
- site:   Adventure Gamers
  type:   Review
  method: find_reviews
- site:   Adventure Gamers
  type:   Database
  method: find_database
  every:  30
- site:   Big Fish Games
  type:   Store
  method: find_adventures
  every:  30
- site:   Big Fish Games
  type:   Store
  method: find_hogs
  every:  30
- site:   Big Fish Games
  type:   Store
  method: find_hopa
  every:  30
- site:   Big Fish Games
  type:   Store
  method: find_puzzles
  every:  30
- site:   GameBoomers
  type:   Review
  method: find_reviews
- site:   GameBoomers
  type:   Walkthrough
  method: find_walkthroughs
- site:   GOG
  type:   Store
  method: find
- site:   Grabbed
  type:   Reference
  method: incremental
- site:   HOTU
  type:   Reference
  method: find_adventure
  every:  30
- site:   HOTU
  type:   Reference
  method: find_puzzle
  every:  30
- site:   HOTU
  type:   Reference
  method: find_rpg
  every:  30
- site:   IGDB
  type:   Reference
  method: find_adventures
- site:   IGDB
  type:   Reference
  method: find_puzzles
- site:   IGDB
  type:   Reference
  method: find_rpgs
- site:   IGDB
  type:   Reference
  method: find_visual_novels
- site:   Just Adventure
  type:   Review
  method: find_reviews
  every:  30
- site:   Just Adventure
  type:   Walkthrough
  method: find_walkthroughs
  every:  30
- site:   Metacritic
  type:   Reference
  method: find_adventures
- site:   Metacritic
  type:   Reference
  method: find_puzzles
- site:   Metacritic
  type:   Reference
  method: find_rpgs
- site:   MobyGames
  type:   Reference
  method: find_adventures
- site:   MobyGames
  type:   Reference
  method: find_jrpgs
- site:   MobyGames
  type:   Reference
  method: find_puzzles
- site:   MobyGames
  type:   Reference
  method: find_rpgs
- site:   MobyGames
  type:   Reference
  method: find_visual_novels
- site:   Mystery Manor
  type:   Review
  method: find_reviews
- site:   Mystery Manor
  type:   Walkthrough
  method: find_walkthroughs
- site:   Nice Game Hints
  type:   Walkthrough
  method: find
- site:   rawg.io
  type:   Reference
  method: find_adventures
- site:   rawg.io
  type:   Reference
  method: find_puzzles
- site:   rawg.io
  type:   Reference
  method: find_rpgs
- site:   Steam
  type:   Store
  method: incremental
  every:  10
- site:   Turn Based Lovers
  type:   Review
  method: find_reviews
test:
- site:   Test
  type:   Test
  method: find1
- site:   Test
  type:   Test
  method: find2
  every:  5
- site:   Test
  type:   Test
  method: find3
  every:  2
incremental:
- site:   TouchArcade
  type:   Review
  method: incremental
full:
- site:   Adventure Game Hotspot
  type:   Database
  method: find_database
rebase:
- site:   TouchArcade
  type:   Review
  method: find
test_full:
- site:   Adventure Game Hotspot
  type:   Database
  method: find_database
test_incremental:
- site:   Mystery Manor
  type:   Walkthrough
  method: find_walkthroughs
- site:   Steam
  type:   Store
  method: find
